# Uncomment the next line to define a global platform for your project
  platform :ios, '12.2'

target 'news-reader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-beta.4'
  pod 'AlamofireImage', '~> 4.0.0-beta.1'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
end
